name: saur_stockist
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  awesome_dialog: ^3.1.0
  cached_network_image: any
  cupertino_icons: ^1.0.2
  dio: ^5.2.1+1
  flashy_tab_bar2: ^0.0.6
  flutter:
    sdk: flutter
  flutter_html: any
  flutter_svg: ^2.0.7
  google_fonts: any
  intl: ^0.18.1
  introduction_screen: ^3.1.8
  line_awesome_flutter: ^2.0.0
  otp_text_field: ^1.1.3
  string_validator: ^1.0.0
  timeago: ^3.4.0
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/banners/
    - assets/images/
    - assets/svg/

flutter_native_splash:
  image: assets/logo/saur_stockist_splash.png
  color: "#194387"
  web_image_mode: cover
  android_gravity: fill
  ios_content_mode: scaleToFill
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/logo_android.png"
  adaptive_icon_background: "#194387"
# flutter pub run flutter_launcher_icons:main
